                            //包含头文件
#include<stdio.h>
#include<string.h>
#include<stdlib.h>
#include<math.h>
#include<windows.h>
#include<conio.h>
#include<time.h>
                             //函数定义头文件
#include".\UI\init_UI.h"
#include".\DAL\data.h"
#include".\DAL\money.h"
#include".\UI\home_UI.h"
#include".\BLL\init_BLL.h"
#include".\DAL\seat_operation.h"
#include".\BLL\user_BLL.h"
#include".\DAL\movie_operation.h"
#include".\DAL\user_operation.h"
#include".\UI\manager_UI.h"
#include".\UI\staff_UI.h"
#include".\UI\tourist_UI.h"
#include".\UI\user_UI.h"
#include".\UI\movie_UI.h"
#include".\BLL\movie_BLL.h"
#include".\UI\seat_UI.h"
#include".\BLL\seat_BLL.h"
#include".\UI\admin_UI.h"
#include".\BLL\money_BLL.h"
#include".\BLL\sort_BLL.h"
                                 //c文件
#include".\DAL\data.c"
#include".\UI\init_UI.c"
#include".\DAL\money.c"
#include".\BLL\init_BLL.c"
#include".\UI\seat_UI.c"
#include".\BLL\seat_BLL.c"
#include".\BLL\movie_BLL.c"
#include".\DAL\seat_operation.c"
#include".\BLL\user_BLL.c"
#include".\DAL\movie_operation.c"
#include".\DAL\user_operation.c"
#include".\UI\home_UI.c"
#include".\UI\manager_UI.c"
#include".\UI\staff_UI.c"
#include".\UI\tourist_UI.c"
#include".\UI\user_UI.c"
#include".\UI\movie_UI.c"
#include".\UI\admin_UI.c"
#include".\BLL\money_BLL.c"
#include".\BLL\sort_BLL.c"




